/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from './mcq-form.component.ngfactory';
import * as import6 from '../../../../src/app/mcq/mcq-form.component';
import * as import7 from '../../../../src/app/services/alert.service';
import * as import8 from '@angular/common';
import * as import9 from '../../../../src/app/mcq/mcq-create.component';
const styles_McqCreateComponent:any[] = ([] as any[]);
export const RenderType_McqCreateComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_McqCreateComponent,
  data: {}
}
);
export function View_McqCreateComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{form: 0}),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Frage erstellen'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'mcq-form',([] as any[]),(null as any),(null as any),(null as any),import5.View_McqFormComponent_0,import5.RenderType_McqFormComponent)),
      import0.ɵdid(4251648,[[
        1,
        4
      ]
    ],0,import6.McqFormComponent,[
      import7.AlertService,
      import4.OlmService,
      import8.Location
    ]
    ,{
      model: [
        0,
        'model'
      ]
      ,
      parent: [
        1,
        'parent'
      ]
      ,
      submitLabel: [
        2,
        'submitLabel'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import9.McqCreateComponent = v.component;
    ck(v,5,0);
    const currVal_0:any = co.model;
    const currVal_1:any = co;
    const currVal_2:any = co.submitLabel;
    ck(v,8,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
function View_McqCreateComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'mcq-create',([] as any[]),(null as any),(null as any),(null as any),View_McqCreateComponent_0,RenderType_McqCreateComponent)),
    import0.ɵdid(57344,(null as any),0,import9.McqCreateComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const McqCreateComponentNgFactory:import0.ComponentFactory<import9.McqCreateComponent> = import0.ɵccf('mcq-create',import9.McqCreateComponent,View_McqCreateComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL21jcS9tY3EtY3JlYXRlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC9tY3EvbWNxLWNyZWF0ZS5jb21wb25lbnQudHMiLCJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC9tY3EvbWNxLWNyZWF0ZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL21jcS9tY3EtY3JlYXRlLmNvbXBvbmVudC50cy5NY3FDcmVhdGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+RnJhZ2UgZXJzdGVsbGVuPC9oMT5cblxuPHRleHQtdmlldz48L3RleHQtdmlldz5cblxuPG1jcS1mb3JtIFttb2RlbF09XCJtb2RlbFwiIFtwYXJlbnRdPVwidGhpc1wiIFtzdWJtaXRMYWJlbF09XCJzdWJtaXRMYWJlbFwiPjwvbWNxLWZvcm0+XG4iLCI8bWNxLWNyZWF0ZT48L21jcS1jcmVhdGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7SUFBb0I7SUFFeEI7Z0JBQUE7Ozs7SUFBQTtLQUFBO0lBQXVCO0lBRXZCO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Ozs7SUFBQTtLQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUFpRjs7OztJQUZqRjtJQUVVO0lBQWdCO0lBQWdCO0lBQTFDLFNBQVUsVUFBZ0IsVUFBZ0IsU0FBMUM7Ozs7O0lDSkE7Z0JBQUE7Ozs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
