/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../src/app/core/alert.component';
import * as import3 from '../../../../src/app/services/alert.service';
const styles_AlertComponent:any[] = ([] as any[]);
export const RenderType_AlertComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AlertComponent,
  data: {}
}
);
function View_AlertComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(139264,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
      ,{ngClass: [
        0,
        'ngClass'
      ]
    },(null as any)),
    import0.ɵpod([
      'alert',
      'alert-success',
      'alert-danger'
    ]
    ),
    (l()(),import0.ɵted((null as any),[
      '\n	',
      '\n'
    ]
    ))
  ]
  ,(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = ck(v,2,0,co.message,(co.message.type === 'success'),(co.message.type === 'error'));
    ck(v,1,0,currVal_0);
  },(ck,v) => {
    var co:any = v.component;
    const currVal_1:any = co.message.text;
    ck(v,3,0,currVal_1);
  });
}
export function View_AlertComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_AlertComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.AlertComponent = v.component;
    const currVal_0:any = co.message;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_AlertComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'alert',([] as any[]),(null as any),(null as any),(null as any),View_AlertComponent_0,RenderType_AlertComponent)),
    import0.ɵdid(57344,(null as any),0,import2.AlertComponent,[import3.AlertService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AlertComponentNgFactory:import0.ComponentFactory<import2.AlertComponent> = import0.ɵccf('alert',import2.AlertComponent,View_AlertComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2NvcmUvYWxlcnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2NvcmUvYWxlcnQuY29tcG9uZW50LnRzIiwibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvY29yZS9hbGVydC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2NvcmUvYWxlcnQuY29tcG9uZW50LnRzLkFsZXJ0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAqbmdJZj1cIm1lc3NhZ2VcIiBbbmdDbGFzc109XCJ7ICdhbGVydCc6IG1lc3NhZ2UsICdhbGVydC1zdWNjZXNzJzogbWVzc2FnZS50eXBlID09PSAnc3VjY2VzcycsICdhbGVydC1kYW5nZXInOiBtZXNzYWdlLnR5cGUgPT09ICdlcnJvcicgfVwiPlxuXHR7e21lc3NhZ2UudGV4dH19XG48L2Rpdj5cbiIsIjxhbGVydD48L2FsZXJ0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO2dCQUFBOzs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBcUI7TUFBQTtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQXdIO01BQUE7TUFBQTtJQUFBO0lBQUE7Ozs7SUFBeEg7SUFBckIsU0FBcUIsU0FBckI7OztJQUE2STtJQUFBOzs7OztJQUE3STtnQkFBQTs7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBRU07Ozs7SUFGRDtJQUFMLFNBQUssU0FBTDs7Ozs7SUNBQTtnQkFBQTs7O0lBQUE7OzsifQ==
