/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from './user-form.component.ngfactory';
import * as import6 from '../../../../src/app/user/user-form.component';
import * as import7 from '../../../../src/app/services/alert.service';
import * as import8 from '@angular/common';
import * as import9 from '../../../../src/app/user/user-edit.component';
const styles_UserEditComponent:any[] = ([] as any[]);
export const RenderType_UserEditComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UserEditComponent,
  data: {}
}
);
export function View_UserEditComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{form: 0}),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Benutzer bearbeiten'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'user-form',([] as any[]),(null as any),(null as any),(null as any),import5.View_UserFormComponent_0,import5.RenderType_UserFormComponent)),
      import0.ɵdid(4218880,[[
        1,
        4
      ]
    ],0,import6.UserFormComponent,[
      import7.AlertService,
      import8.Location
    ]
    ,{
      model: [
        0,
        'model'
      ]
      ,
      parent: [
        1,
        'parent'
      ]
      ,
      submitLabel: [
        2,
        'submitLabel'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import9.UserEditComponent = v.component;
    ck(v,5,0);
    const currVal_0:any = co.model;
    const currVal_1:any = co;
    const currVal_2:any = co.submitLabel;
    ck(v,8,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
function View_UserEditComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'user-edit',([] as any[]),(null as any),(null as any),(null as any),View_UserEditComponent_0,RenderType_UserEditComponent)),
    import0.ɵdid(57344,(null as any),0,import9.UserEditComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router,
      import8.Location
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UserEditComponentNgFactory:import0.ComponentFactory<import9.UserEditComponent> = import0.ɵccf('user-edit',import9.UserEditComponent,View_UserEditComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3VzZXIvdXNlci1lZGl0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC91c2VyL3VzZXItZWRpdC5jb21wb25lbnQudHMiLCJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC91c2VyL3VzZXItZWRpdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3VzZXIvdXNlci1lZGl0LmNvbXBvbmVudC50cy5Vc2VyRWRpdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5CZW51dHplciBiZWFyYmVpdGVuPC9oMT5cblxuPHRleHQtdmlldz48L3RleHQtdmlldz5cblxuPHVzZXItZm9ybSBbbW9kZWxdPVwibW9kZWxcIiBbcGFyZW50XT1cInRoaXNcIiBbc3VibWl0TGFiZWxdPVwic3VibWl0TGFiZWxcIj48L3VzZXItZm9ybT5cbiIsIjx1c2VyLWVkaXQ+PC91c2VyLWVkaXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7SUFBd0I7SUFFNUI7Z0JBQUE7Ozs7SUFBQTtLQUFBO0lBQXVCO0lBRXZCO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7OztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQW1GOzs7O0lBRm5GO0lBRVc7SUFBZ0I7SUFBZ0I7SUFBM0MsU0FBVyxVQUFnQixVQUFnQixTQUEzQzs7Ozs7SUNKQTtnQkFBQTs7Ozs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
