/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from './user-form.component.ngfactory';
import * as import6 from '../../../../src/app/user/user-form.component';
import * as import7 from '../../../../src/app/services/alert.service';
import * as import8 from '@angular/common';
import * as import9 from '../../../../src/app/user/user-create.component';
const styles_UserCreateComponent:any[] = ([] as any[]);
export const RenderType_UserCreateComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UserCreateComponent,
  data: {}
}
);
export function View_UserCreateComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{form: 0}),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Benutzer einladen'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'user-form',([] as any[]),(null as any),(null as any),(null as any),import5.View_UserFormComponent_0,import5.RenderType_UserFormComponent)),
      import0.ɵdid(4218880,[[
        1,
        4
      ]
    ],0,import6.UserFormComponent,[
      import7.AlertService,
      import8.Location
    ]
    ,{
      model: [
        0,
        'model'
      ]
      ,
      parent: [
        1,
        'parent'
      ]
      ,
      submitLabel: [
        2,
        'submitLabel'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import9.UserCreateComponent = v.component;
    ck(v,5,0);
    const currVal_0:any = co.model;
    const currVal_1:any = co;
    const currVal_2:any = co.submitLabel;
    ck(v,8,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
function View_UserCreateComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'user-create',([] as any[]),(null as any),(null as any),(null as any),View_UserCreateComponent_0,RenderType_UserCreateComponent)),
    import0.ɵdid(24576,(null as any),0,import9.UserCreateComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UserCreateComponentNgFactory:import0.ComponentFactory<import9.UserCreateComponent> = import0.ɵccf('user-create',import9.UserCreateComponent,View_UserCreateComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3VzZXIvdXNlci1jcmVhdGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3VzZXIvdXNlci1jcmVhdGUuY29tcG9uZW50LnRzIiwibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvdXNlci91c2VyLWNyZWF0ZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3VzZXIvdXNlci1jcmVhdGUuY29tcG9uZW50LnRzLlVzZXJDcmVhdGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+QmVudXR6ZXIgZWlubGFkZW48L2gxPlxuXG48dGV4dC12aWV3PjwvdGV4dC12aWV3PlxuXG48dXNlci1mb3JtIFttb2RlbF09XCJtb2RlbFwiIFtwYXJlbnRdPVwidGhpc1wiIFtzdWJtaXRMYWJlbF09XCJzdWJtaXRMYWJlbFwiPjwvdXNlci1mb3JtPlxuIiwiPHVzZXItY3JlYXRlPjwvdXNlci1jcmVhdGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7SUFBc0I7SUFFMUI7Z0JBQUE7Ozs7SUFBQTtLQUFBO0lBQXVCO0lBRXZCO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7OztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQW1GOzs7O0lBRm5GO0lBRVc7SUFBZ0I7SUFBZ0I7SUFBM0MsU0FBVyxVQUFnQixVQUFnQixTQUEzQzs7Ozs7SUNKQTtnQkFBQTs7Ozs7SUFBQTtLQUFBOzs7OyJ9
