/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/module/module-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './module-create.component.ngfactory';
import * as import4 from './module-edit.component.ngfactory';
import * as import5 from '../../../../src/app/module/module-create.component';
import * as import6 from '../../../../src/app/services/olm.service';
import * as import7 from '../../../../src/app/module/module-edit.component';
class ModuleRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ModuleRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ModuleRoutingModule_1:import1.ModuleRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.ModuleCreateComponentNgFactory,
      import4.ModuleEditComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.ModuleRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ModuleRoutingModule_1 = new import1.ModuleRoutingModule();
      this._ROUTES_2 = [[
        {
          path: 'module/create',
          component: import5.ModuleCreateComponent,
          canActivate: [import6.OlmService]
        }
        ,
        {
          path: 'module/edit/:id/:version',
          component: import7.ModuleEditComponent,
          canActivate: [import6.OlmService]
        }

      ]
    ];
    return this._ModuleRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ModuleRoutingModule)) { return this._ModuleRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ModuleRoutingModuleNgFactory:import0.NgModuleFactory<import1.ModuleRoutingModule> = new import0.NgModuleFactory<any>(ModuleRoutingModuleInjector,import1.ModuleRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL21vZHVsZS9tb2R1bGUtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvbW9kdWxlL21vZHVsZS1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
