/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from '@angular/common';
import * as import6 from '../../../../src/app/protocoll/protocoll-view.component';
import * as import7 from '../../../../src/app/services/alert.service';
const styles_ProtocollViewComponent:any[] = ([] as any[]);
export const RenderType_ProtocollViewComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProtocollViewComponent,
  data: {}
}
);
export function View_ProtocollViewComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n\n'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),6,'menu',[[
        'class',
        'bottom'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n	'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'a',[[
        'class',
        'btn btn-back'
      ]
    ],[
      [
        1,
        'target',
        0
      ]
      ,
      [
        8,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('click' === en)) {
        const pd_0:any = ((<any>import0.ɵnov(v,12).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import0.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import5.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import0.ɵpad(2),
    (l()(),import0.ɵted((null as any),['zurück'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import6.ProtocollViewComponent = v.component;
    ck(v,4,0);
    const currVal_4:any = ck(v,13,0,'/protocolls/view',co.exam);
    ck(v,12,0,currVal_4);
  },(ck,v) => {
    var co:import6.ProtocollViewComponent = v.component;
    const currVal_0:any = co.item.name;
    ck(v,1,0,currVal_0);
    const currVal_1:any = co.item.text;
    ck(v,7,0,currVal_1);
    const currVal_2:any = import0.ɵnov(v,12).target;
    const currVal_3:any = import0.ɵnov(v,12).href;
    ck(v,11,0,currVal_2,currVal_3);
  });
}
function View_ProtocollViewComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'protocoll-view',([] as any[]),(null as any),(null as any),(null as any),View_ProtocollViewComponent_0,RenderType_ProtocollViewComponent)),
    import0.ɵdid(57344,(null as any),0,import6.ProtocollViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ProtocollViewComponentNgFactory:import0.ComponentFactory<import6.ProtocollViewComponent> = import0.ɵccf('protocoll-view',import6.ProtocollViewComponent,View_ProtocollViewComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtdmlldy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvcHJvdG9jb2xsL3Byb3RvY29sbC12aWV3LmNvbXBvbmVudC50cyIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtdmlldy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtdmlldy5jb21wb25lbnQudHMuUHJvdG9jb2xsVmlld0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT57e2l0ZW0ubmFtZX19PC9oMT5cblxuPHRleHQtdmlldz48L3RleHQtdmlldz5cblxuPHByZT57e2l0ZW0udGV4dH19PC9wcmU+XG5cbjxtZW51IGNsYXNzPVwiYm90dG9tXCI+XG5cdDxhIGNsYXNzPVwiYnRuIGJ0bi1iYWNrXCIgW3JvdXRlckxpbmtdPVwiWycvcHJvdG9jb2xscy92aWV3JywgZXhhbV1cIj56dXLDvGNrPC9hPlxuPC9tZW51PlxuIiwiPHByb3RvY29sbC12aWV3PjwvcHJvdG9jb2xsLXZpZXc+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFrQjtJQUV0QjtnQkFBQTs7OztJQUFBO0tBQUE7SUFBdUI7SUFFdkI7SUFBSztNQUFBO01BQUE7SUFBQTtJQUFBO0lBQW1CO01BRXhCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBcUI7TUFDcEI7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO01BQUE7SUFBQTtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBd0I7SUFBMEM7SUFBVTtJQUN0RTs7OztJQU5QO0lBS3lCO0lBQXhCLFVBQXdCLFNBQXhCOzs7SUFQRztJQUFBO0lBSUM7SUFBQTtJQUdKO0lBQUE7SUFBQSxVQUFBLG1CQUFBOzs7OztJQ1BEO2dCQUFBOzs7OztJQUFBO0tBQUE7OztJQUFBOzs7In0=
