/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from './protocoll-form.component.ngfactory';
import * as import6 from '../../../../src/app/protocoll/protocoll-form.component';
import * as import7 from '../../../../src/app/services/alert.service';
import * as import8 from '@angular/common';
import * as import9 from '../../../../src/app/protocoll/protocoll-edit.component';
const styles_ProtocollEditComponent:any[] = ([] as any[]);
export const RenderType_ProtocollEditComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProtocollEditComponent,
  data: {}
}
);
export function View_ProtocollEditComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{form: 0}),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Protokoll bearbeiten'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'protocoll-form',([] as any[]),(null as any),(null as any),(null as any),import5.View_ProtocollFormComponent_0,import5.RenderType_ProtocollFormComponent)),
      import0.ɵdid(4218880,[[
        1,
        4
      ]
    ],0,import6.ProtocollFormComponent,[
      import7.AlertService,
      import8.Location
    ]
    ,{
      model: [
        0,
        'model'
      ]
      ,
      parent: [
        1,
        'parent'
      ]
      ,
      submitLabel: [
        2,
        'submitLabel'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import9.ProtocollEditComponent = v.component;
    ck(v,5,0);
    const currVal_0:any = co.model;
    const currVal_1:any = co;
    const currVal_2:any = co.submitLabel;
    ck(v,8,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
function View_ProtocollEditComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'protocoll-edit',([] as any[]),(null as any),(null as any),(null as any),View_ProtocollEditComponent_0,RenderType_ProtocollEditComponent)),
    import0.ɵdid(57344,(null as any),0,import9.ProtocollEditComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router,
      import8.Location
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ProtocollEditComponentNgFactory:import0.ComponentFactory<import9.ProtocollEditComponent> = import0.ɵccf('protocoll-edit',import9.ProtocollEditComponent,View_ProtocollEditComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtZWRpdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvcHJvdG9jb2xsL3Byb3RvY29sbC1lZGl0LmNvbXBvbmVudC50cyIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtZWRpdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Byb3RvY29sbC9wcm90b2NvbGwtZWRpdC5jb21wb25lbnQudHMuUHJvdG9jb2xsRWRpdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Qcm90b2tvbGwgYmVhcmJlaXRlbjwvaDE+XG5cbjx0ZXh0LXZpZXc+PC90ZXh0LXZpZXc+XG5cbjxwcm90b2NvbGwtZm9ybSBbbW9kZWxdPVwibW9kZWxcIiBbcGFyZW50XT1cInRoaXNcIiBbc3VibWl0TGFiZWxdPVwic3VibWl0TGFiZWxcIj48L3Byb3RvY29sbC1mb3JtPlxuIiwiPHByb3RvY29sbC1lZGl0PjwvcHJvdG9jb2xsLWVkaXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7SUFBeUI7SUFFN0I7Z0JBQUE7Ozs7SUFBQTtLQUFBO0lBQXVCO0lBRXZCO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7OztJQUFBO0tBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQTZGOzs7O0lBRjdGO0lBRWdCO0lBQWdCO0lBQWdCO0lBQWhELFNBQWdCLFVBQWdCLFVBQWdCLFNBQWhEOzs7OztJQ0pBO2dCQUFBOzs7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
