/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/session/session-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './session-create.component.ngfactory';
import * as import4 from './session-view.component.ngfactory';
import * as import5 from '../../../../src/app/session/session-create.component';
import * as import6 from '../../../../src/app/services/olm.service';
import * as import7 from '../../../../src/app/session/session-view.component';
class SessionRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.SessionRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _SessionRoutingModule_1:import1.SessionRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.SessionCreateComponentNgFactory,
      import4.SessionViewComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.SessionRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._SessionRoutingModule_1 = new import1.SessionRoutingModule();
      this._ROUTES_2 = [[
        {
          path: 'session/create',
          component: import5.SessionCreateComponent,
          canActivate: [import6.OlmService]
        }
        ,
        {
          path: 'session/view/:id',
          component: import7.SessionViewComponent,
          canActivate: [import6.OlmService]
        }

      ]
    ];
    return this._SessionRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.SessionRoutingModule)) { return this._SessionRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SessionRoutingModuleNgFactory:import0.NgModuleFactory<import1.SessionRoutingModule> = new import0.NgModuleFactory<any>(SessionRoutingModuleInjector,import1.SessionRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3Nlc3Npb24vc2Vzc2lvbi1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC9zZXNzaW9uL3Nlc3Npb24tcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
