/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/router';
import * as import4 from '@angular/common';
import * as import5 from '@angular/platform-browser';
import * as import6 from '@angular/forms';
import * as import7 from '../../../src/app/shared/shared.module';
import * as import8 from '../../../src/app/core/core-routing.module';
import * as import9 from '../../../src/app/core/core.module';
import * as import10 from '../../../src/app/module/module-routing.module';
import * as import11 from '../../../src/app/module/module.module';
import * as import12 from '../../../src/app/exam/exam-routing.module';
import * as import13 from '../../../src/app/exam/exam.module';
import * as import14 from '../../../src/app/user/user-routing.module';
import * as import15 from '../../../src/app/user/user.module';
import * as import16 from '../../../src/app/mcq/mcq-routing.module';
import * as import17 from '../../../src/app/mcq/mcq.module';
import * as import18 from '../../../src/app/session/session-routing.module';
import * as import19 from '../../../src/app/session/session.module';
import * as import20 from '../../../src/app/protocoll/protocoll-routing.module';
import * as import21 from '../../../src/app/protocoll/protocoll.module';
import * as import22 from '../../../src/app/text/text-routing.module';
import * as import23 from '../../../src/app/text/text.module';
import * as import24 from '../../../src/app/app-routing.module';
import * as import25 from '../../../src/app/services/alert.service';
import * as import26 from '../../../src/app/services/olm.service';
import * as import27 from './core/door.component.ngfactory';
import * as import28 from './core/dashboard.component.ngfactory';
import * as import29 from './core/door-reset.component.ngfactory';
import * as import30 from './core/delete.component.ngfactory';
import * as import31 from './core/deleted.component.ngfactory';
import * as import32 from './core/history.component.ngfactory';
import * as import33 from './module/module-create.component.ngfactory';
import * as import34 from './module/module-edit.component.ngfactory';
import * as import35 from './exam/exam-create.component.ngfactory';
import * as import36 from './exam/exam-edit.component.ngfactory';
import * as import37 from './user/user-create.component.ngfactory';
import * as import38 from './user/user-edit.component.ngfactory';
import * as import39 from './user/users-view.component.ngfactory';
import * as import40 from './mcq/mcq-create.component.ngfactory';
import * as import41 from './mcq/mcq-edit.component.ngfactory';
import * as import42 from './mcq/mcq-view.component.ngfactory';
import * as import43 from './mcq/mcqs-view.component.ngfactory';
import * as import44 from './session/session-create.component.ngfactory';
import * as import45 from './session/session-view.component.ngfactory';
import * as import46 from './protocoll/protocoll-create.component.ngfactory';
import * as import47 from './protocoll/protocoll-edit.component.ngfactory';
import * as import48 from './protocoll/protocolls-view.component.ngfactory';
import * as import49 from './protocoll/protocoll-view.component.ngfactory';
import * as import50 from './text/text-create.component.ngfactory';
import * as import51 from './text/text-edit.component.ngfactory';
import * as import52 from './text/texts-view.component.ngfactory';
import * as import53 from './app.component.ngfactory';
import * as import54 from '../../../src/app/core/door.component';
import * as import55 from '../../../src/app/core/dashboard.component';
import * as import56 from '../../../src/app/core/door-reset.component';
import * as import57 from '../../../src/app/core/delete.component';
import * as import58 from '../../../src/app/core/deleted.component';
import * as import59 from '../../../src/app/core/history.component';
import * as import60 from '../../../src/app/module/module-create.component';
import * as import61 from '../../../src/app/module/module-edit.component';
import * as import62 from '../../../src/app/exam/exam-create.component';
import * as import63 from '../../../src/app/exam/exam-edit.component';
import * as import64 from '../../../src/app/user/user-create.component';
import * as import65 from '../../../src/app/user/user-edit.component';
import * as import66 from '../../../src/app/user/users-view.component';
import * as import67 from '../../../src/app/mcq/mcq-create.component';
import * as import68 from '../../../src/app/mcq/mcq-edit.component';
import * as import69 from '../../../src/app/mcq/mcq-view.component';
import * as import70 from '../../../src/app/mcq/mcqs-view.component';
import * as import71 from '../../../src/app/session/session-create.component';
import * as import72 from '../../../src/app/session/session-view.component';
import * as import73 from '../../../src/app/protocoll/protocoll-create.component';
import * as import74 from '../../../src/app/protocoll/protocoll-edit.component';
import * as import75 from '../../../src/app/protocoll/protocolls-view.component';
import * as import76 from '../../../src/app/protocoll/protocoll-view.component';
import * as import77 from '../../../src/app/text/text-create.component';
import * as import78 from '../../../src/app/text/text-edit.component';
import * as import79 from '../../../src/app/text/texts-view.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _HttpModule_0:import2.HttpModule;
  _ɵa_1:any;
  _ErrorHandler_2:any;
  _NgProbeToken_3:any[];
  _ɵg_4:import3.ɵg;
  _APP_INITIALIZER_5:any[];
  _ApplicationInitStatus_6:import0.ApplicationInitStatus;
  _ɵf_7:import0.ɵf;
  _ApplicationRef_8:any;
  _UrlSerializer_9:import3.DefaultUrlSerializer;
  _RouterOutletMap_10:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_11:any;
  _LocationStrategy_12:any;
  _Location_13:import4.Location;
  _Compiler_14:import0.Compiler;
  _NgModuleFactoryLoader_15:import0.SystemJsNgModuleLoader;
  _ROUTES_16:any[];
  _Router_17:any;
  _RouterModule_18:import3.RouterModule;
  _CommonModule_19:import4.CommonModule;
  _ApplicationModule_20:import0.ApplicationModule;
  _BrowserModule_21:import5.BrowserModule;
  _ɵba_22:import6.ɵba;
  _FormsModule_23:import6.FormsModule;
  _SharedModule_24:import7.SharedModule;
  _CoreRoutingModule_25:import8.CoreRoutingModule;
  _CoreModule_26:import9.CoreModule;
  _ModuleRoutingModule_27:import10.ModuleRoutingModule;
  _ModuleModule_28:import11.ModuleModule;
  _ExamRoutingModule_29:import12.ExamRoutingModule;
  _ExamModule_30:import13.ExamModule;
  _UserRoutingModule_31:import14.UserRoutingModule;
  _UserModule_32:import15.UserModule;
  _McqRoutingModule_33:import16.McqRoutingModule;
  _McqModule_34:import17.McqModule;
  _SessionRoutingModule_35:import18.SessionRoutingModule;
  _SessionModule_36:import19.SessionModule;
  _ProtocollRoutingModule_37:import20.ProtocollRoutingModule;
  _ProtocollModule_38:import21.ProtocollModule;
  _TextRoutingModule_39:import22.TextRoutingModule;
  _TextModule_40:import23.TextModule;
  _AppRoutingModule_41:import24.AppRoutingModule;
  _AppModule_42:import1.AppModule;
  __BrowserXhr_43:import2.BrowserXhr;
  __ResponseOptions_44:import2.BaseResponseOptions;
  __XSRFStrategy_45:any;
  __XHRBackend_46:import2.XHRBackend;
  __RequestOptions_47:import2.BaseRequestOptions;
  __Http_48:any;
  __LOCALE_ID_49:any;
  __NgLocalization_50:import4.NgLocaleLocalization;
  __APP_ID_51:any;
  __IterableDiffers_52:any;
  __KeyValueDiffers_53:any;
  __DomSanitizer_54:import5.ɵe;
  __Sanitizer_55:any;
  __HAMMER_GESTURE_CONFIG_56:import5.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_57:any[];
  __EventManager_58:import5.EventManager;
  __ɵDomSharedStylesHost_59:import5.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_60:import5.ɵDomRendererFactory2;
  __RendererFactory2_61:any;
  __ɵSharedStylesHost_62:any;
  __Testability_63:import0.Testability;
  __Meta_64:import5.Meta;
  __Title_65:import5.Title;
  __ɵi_66:import6.ɵi;
  __ActivatedRoute_67:any;
  __NoPreloading_68:import3.NoPreloading;
  __PreloadingStrategy_69:any;
  __RouterPreloader_70:import3.RouterPreloader;
  __PreloadAllModules_71:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_72:any;
  __APP_BOOTSTRAP_LISTENER_73:any[];
  __AlertService_74:import25.AlertService;
  __OlmService_75:import26.OlmService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import27.DoorComponentNgFactory,
      import28.DashboardComponentNgFactory,
      import29.DoorResetComponentNgFactory,
      import30.DeleteComponentNgFactory,
      import31.DeletedComponentNgFactory,
      import32.HistoryComponentNgFactory,
      import33.ModuleCreateComponentNgFactory,
      import34.ModuleEditComponentNgFactory,
      import35.ExamCreateComponentNgFactory,
      import36.ExamEditComponentNgFactory,
      import37.UserCreateComponentNgFactory,
      import38.UserEditComponentNgFactory,
      import39.UsersViewComponentNgFactory,
      import40.McqCreateComponentNgFactory,
      import41.McqEditComponentNgFactory,
      import42.McqViewComponentNgFactory,
      import43.McqsViewComponentNgFactory,
      import44.SessionCreateComponentNgFactory,
      import45.SessionViewComponentNgFactory,
      import46.ProtocollCreateComponentNgFactory,
      import47.ProtocollEditComponentNgFactory,
      import48.ProtocollsViewComponentNgFactory,
      import49.ProtocollViewComponentNgFactory,
      import50.TextCreateComponentNgFactory,
      import51.TextEditComponentNgFactory,
      import52.TextsViewComponentNgFactory,
      import53.AppComponentNgFactory
    ]
    ,[import53.AppComponentNgFactory]);
  }
  get _BrowserXhr_43():import2.BrowserXhr {
    if ((this.__BrowserXhr_43 == null)) { (this.__BrowserXhr_43 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_43;
  }
  get _ResponseOptions_44():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_44 == null)) { (this.__ResponseOptions_44 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_44;
  }
  get _XSRFStrategy_45():any {
    if ((this.__XSRFStrategy_45 == null)) { (this.__XSRFStrategy_45 = import2.ɵb()); }
    return this.__XSRFStrategy_45;
  }
  get _XHRBackend_46():import2.XHRBackend {
    if ((this.__XHRBackend_46 == null)) { (this.__XHRBackend_46 = new import2.XHRBackend(this._BrowserXhr_43,this._ResponseOptions_44,this._XSRFStrategy_45)); }
    return this.__XHRBackend_46;
  }
  get _RequestOptions_47():import2.BaseRequestOptions {
    if ((this.__RequestOptions_47 == null)) { (this.__RequestOptions_47 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_47;
  }
  get _Http_48():any {
    if ((this.__Http_48 == null)) { (this.__Http_48 = import2.ɵc(this._XHRBackend_46,this._RequestOptions_47)); }
    return this.__Http_48;
  }
  get _LOCALE_ID_49():any {
    if ((this.__LOCALE_ID_49 == null)) { (this.__LOCALE_ID_49 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_49;
  }
  get _NgLocalization_50():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_50 == null)) { (this.__NgLocalization_50 = new import4.NgLocaleLocalization(this._LOCALE_ID_49)); }
    return this.__NgLocalization_50;
  }
  get _APP_ID_51():any {
    if ((this.__APP_ID_51 == null)) { (this.__APP_ID_51 = import0.ɵg()); }
    return this.__APP_ID_51;
  }
  get _IterableDiffers_52():any {
    if ((this.__IterableDiffers_52 == null)) { (this.__IterableDiffers_52 = import0.ɵl()); }
    return this.__IterableDiffers_52;
  }
  get _KeyValueDiffers_53():any {
    if ((this.__KeyValueDiffers_53 == null)) { (this.__KeyValueDiffers_53 = import0.ɵm()); }
    return this.__KeyValueDiffers_53;
  }
  get _DomSanitizer_54():import5.ɵe {
    if ((this.__DomSanitizer_54 == null)) { (this.__DomSanitizer_54 = new import5.ɵe(this.parent.get(import5.DOCUMENT))); }
    return this.__DomSanitizer_54;
  }
  get _Sanitizer_55():any {
    if ((this.__Sanitizer_55 == null)) { (this.__Sanitizer_55 = this._DomSanitizer_54); }
    return this.__Sanitizer_55;
  }
  get _HAMMER_GESTURE_CONFIG_56():import5.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_56 == null)) { (this.__HAMMER_GESTURE_CONFIG_56 = new import5.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_56;
  }
  get _EVENT_MANAGER_PLUGINS_57():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_57 == null)) { (this.__EVENT_MANAGER_PLUGINS_57 = [
      new import5.ɵDomEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵKeyEventsPlugin(this.parent.get(import5.DOCUMENT)),
      new import5.ɵHammerGesturesPlugin(this.parent.get(import5.DOCUMENT),this._HAMMER_GESTURE_CONFIG_56)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_57;
  }
  get _EventManager_58():import5.EventManager {
    if ((this.__EventManager_58 == null)) { (this.__EventManager_58 = new import5.EventManager(this._EVENT_MANAGER_PLUGINS_57,this.parent.get(import0.NgZone))); }
    return this.__EventManager_58;
  }
  get _ɵDomSharedStylesHost_59():import5.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_59 == null)) { (this.__ɵDomSharedStylesHost_59 = new import5.ɵDomSharedStylesHost(this.parent.get(import5.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_59;
  }
  get _ɵDomRendererFactory2_60():import5.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_60 == null)) { (this.__ɵDomRendererFactory2_60 = new import5.ɵDomRendererFactory2(this._EventManager_58,this._ɵDomSharedStylesHost_59)); }
    return this.__ɵDomRendererFactory2_60;
  }
  get _RendererFactory2_61():any {
    if ((this.__RendererFactory2_61 == null)) { (this.__RendererFactory2_61 = this._ɵDomRendererFactory2_60); }
    return this.__RendererFactory2_61;
  }
  get _ɵSharedStylesHost_62():any {
    if ((this.__ɵSharedStylesHost_62 == null)) { (this.__ɵSharedStylesHost_62 = this._ɵDomSharedStylesHost_59); }
    return this.__ɵSharedStylesHost_62;
  }
  get _Testability_63():import0.Testability {
    if ((this.__Testability_63 == null)) { (this.__Testability_63 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_63;
  }
  get _Meta_64():import5.Meta {
    if ((this.__Meta_64 == null)) { (this.__Meta_64 = new import5.Meta(this.parent.get(import5.DOCUMENT))); }
    return this.__Meta_64;
  }
  get _Title_65():import5.Title {
    if ((this.__Title_65 == null)) { (this.__Title_65 = new import5.Title(this.parent.get(import5.DOCUMENT))); }
    return this.__Title_65;
  }
  get _ɵi_66():import6.ɵi {
    if ((this.__ɵi_66 == null)) { (this.__ɵi_66 = new import6.ɵi()); }
    return this.__ɵi_66;
  }
  get _ActivatedRoute_67():any {
    if ((this.__ActivatedRoute_67 == null)) { (this.__ActivatedRoute_67 = import3.ɵf(this._Router_17)); }
    return this.__ActivatedRoute_67;
  }
  get _NoPreloading_68():import3.NoPreloading {
    if ((this.__NoPreloading_68 == null)) { (this.__NoPreloading_68 = new import3.NoPreloading()); }
    return this.__NoPreloading_68;
  }
  get _PreloadingStrategy_69():any {
    if ((this.__PreloadingStrategy_69 == null)) { (this.__PreloadingStrategy_69 = this._NoPreloading_68); }
    return this.__PreloadingStrategy_69;
  }
  get _RouterPreloader_70():import3.RouterPreloader {
    if ((this.__RouterPreloader_70 == null)) { (this.__RouterPreloader_70 = new import3.RouterPreloader(this._Router_17,this._NgModuleFactoryLoader_15,this._Compiler_14,this,this._PreloadingStrategy_69)); }
    return this.__RouterPreloader_70;
  }
  get _PreloadAllModules_71():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_71 == null)) { (this.__PreloadAllModules_71 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_71;
  }
  get _ROUTER_INITIALIZER_72():any {
    if ((this.__ROUTER_INITIALIZER_72 == null)) { (this.__ROUTER_INITIALIZER_72 = import3.ɵi(this._ɵg_4)); }
    return this.__ROUTER_INITIALIZER_72;
  }
  get _APP_BOOTSTRAP_LISTENER_73():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_73 == null)) { (this.__APP_BOOTSTRAP_LISTENER_73 = [this._ROUTER_INITIALIZER_72]); }
    return this.__APP_BOOTSTRAP_LISTENER_73;
  }
  get _AlertService_74():import25.AlertService {
    if ((this.__AlertService_74 == null)) { (this.__AlertService_74 = new import25.AlertService(this._Router_17)); }
    return this.__AlertService_74;
  }
  get _OlmService_75():import26.OlmService {
    if ((this.__OlmService_75 == null)) { (this.__OlmService_75 = new import26.OlmService(this._Http_48,this._Router_17)); }
    return this.__OlmService_75;
  }
  createInternal():import1.AppModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._ɵa_1 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._ErrorHandler_2 = import5.ɵa();
    this._NgProbeToken_3 = [import3.ɵb()];
    this._ɵg_4 = new import3.ɵg(this);
    this._APP_INITIALIZER_5 = [
      import0.ɵo,
      import5.ɵc(this.parent.get(import5.NgProbeToken,(null as any)),this._NgProbeToken_3),
      import3.ɵh(this._ɵg_4)
    ]
    ;
    this._ApplicationInitStatus_6 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_5);
    this._ɵf_7 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_6);
    this._ApplicationRef_8 = this._ɵf_7;
    this._UrlSerializer_9 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_10 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_11 = {};
    this._LocationStrategy_12 = import3.ɵc(this.parent.get(import4.PlatformLocation),this.parent.get(import4.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_11);
    this._Location_13 = new import4.Location(this._LocationStrategy_12);
    this._Compiler_14 = new import0.Compiler();
    this._NgModuleFactoryLoader_15 = new import0.SystemJsNgModuleLoader(this._Compiler_14,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_16 = [
      [
        {
          path: 'door',
          component: import54.DoorComponent
        }
        ,
        {
          path: 'dashboard',
          component: import55.DashboardComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'door/reset',
          component: import56.DoorResetComponent
        }
        ,
        {
          path: ':type/delete/:id',
          component: import57.DeleteComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: ':type/deleted',
          component: import58.DeletedComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: ':type/history/:id',
          component: import59.HistoryComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'module/create',
          component: import60.ModuleCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'module/edit/:id/:version',
          component: import61.ModuleEditComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'exam/create',
          component: import62.ExamCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'exam/edit/:id/:version',
          component: import63.ExamEditComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'user/create',
          component: import64.UserCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'user/edit/:id',
          component: import65.UserEditComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'users/view',
          component: import66.UsersViewComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'mcq/create/:moduleid',
          component: import67.McqCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'mcq/edit/:id/:version',
          component: import68.McqEditComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'mcq/view/:id',
          component: import69.McqViewComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'mcqs/view/:module/:rating/:generation/:original/:number',
          component: import70.McqsViewComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'session/create',
          component: import71.SessionCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'session/view/:id',
          component: import72.SessionViewComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'protocoll/create/:examid',
          component: import73.ProtocollCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'protocoll/edit/:id/:version',
          component: import74.ProtocollEditComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'protocolls/view/:examid',
          component: import75.ProtocollsViewComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'protocoll/view/:id',
          component: import76.ProtocollViewComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: 'text/create/:id',
          component: import77.TextCreateComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'text/edit/:id/:version',
          component: import78.TextEditComponent,
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: 'texts/view',
          component: import79.TextsViewComponent,
          canActivate: [import26.OlmService]
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: 'dashboard',
          pathMatch: 'full',
          canActivate: [import26.OlmService]
        }
        ,
        {
          path: '**',
          redirectTo: 'dashboard',
          pathMatch: 'full',
          canActivate: [import26.OlmService]
        }

      ]

    ]
    ;
    this._Router_17 = import3.ɵe(this._ApplicationRef_8,this._UrlSerializer_9,this._RouterOutletMap_10,this._Location_13,this,this._NgModuleFactoryLoader_15,this._Compiler_14,this._ROUTES_16,this._ROUTER_CONFIGURATION_11,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_18 = new import3.RouterModule(this._ɵa_1,this._Router_17);
    this._CommonModule_19 = new import4.CommonModule();
    this._ApplicationModule_20 = new import0.ApplicationModule(this._ApplicationRef_8);
    this._BrowserModule_21 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._ɵba_22 = new import6.ɵba();
    this._FormsModule_23 = new import6.FormsModule();
    this._SharedModule_24 = new import7.SharedModule();
    this._CoreRoutingModule_25 = new import8.CoreRoutingModule();
    this._CoreModule_26 = new import9.CoreModule(this.parent.get(import9.CoreModule,(null as any)));
    this._ModuleRoutingModule_27 = new import10.ModuleRoutingModule();
    this._ModuleModule_28 = new import11.ModuleModule();
    this._ExamRoutingModule_29 = new import12.ExamRoutingModule();
    this._ExamModule_30 = new import13.ExamModule();
    this._UserRoutingModule_31 = new import14.UserRoutingModule();
    this._UserModule_32 = new import15.UserModule();
    this._McqRoutingModule_33 = new import16.McqRoutingModule();
    this._McqModule_34 = new import17.McqModule();
    this._SessionRoutingModule_35 = new import18.SessionRoutingModule();
    this._SessionModule_36 = new import19.SessionModule();
    this._ProtocollRoutingModule_37 = new import20.ProtocollRoutingModule();
    this._ProtocollModule_38 = new import21.ProtocollModule();
    this._TextRoutingModule_39 = new import22.TextRoutingModule();
    this._TextModule_40 = new import23.TextModule();
    this._AppRoutingModule_41 = new import24.AppRoutingModule();
    this._AppModule_42 = new import1.AppModule();
    return this._AppModule_42;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.ɵa)) { return this._ɵa_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_3; }
    if ((token === import3.ɵg)) { return this._ɵg_4; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_5; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_6; }
    if ((token === import0.ɵf)) { return this._ɵf_7; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_8; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_9; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_10; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_11; }
    if ((token === import4.LocationStrategy)) { return this._LocationStrategy_12; }
    if ((token === import4.Location)) { return this._Location_13; }
    if ((token === import0.Compiler)) { return this._Compiler_14; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_15; }
    if ((token === import3.ROUTES)) { return this._ROUTES_16; }
    if ((token === import3.Router)) { return this._Router_17; }
    if ((token === import3.RouterModule)) { return this._RouterModule_18; }
    if ((token === import4.CommonModule)) { return this._CommonModule_19; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_20; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_21; }
    if ((token === import6.ɵba)) { return this._ɵba_22; }
    if ((token === import6.FormsModule)) { return this._FormsModule_23; }
    if ((token === import7.SharedModule)) { return this._SharedModule_24; }
    if ((token === import8.CoreRoutingModule)) { return this._CoreRoutingModule_25; }
    if ((token === import9.CoreModule)) { return this._CoreModule_26; }
    if ((token === import10.ModuleRoutingModule)) { return this._ModuleRoutingModule_27; }
    if ((token === import11.ModuleModule)) { return this._ModuleModule_28; }
    if ((token === import12.ExamRoutingModule)) { return this._ExamRoutingModule_29; }
    if ((token === import13.ExamModule)) { return this._ExamModule_30; }
    if ((token === import14.UserRoutingModule)) { return this._UserRoutingModule_31; }
    if ((token === import15.UserModule)) { return this._UserModule_32; }
    if ((token === import16.McqRoutingModule)) { return this._McqRoutingModule_33; }
    if ((token === import17.McqModule)) { return this._McqModule_34; }
    if ((token === import18.SessionRoutingModule)) { return this._SessionRoutingModule_35; }
    if ((token === import19.SessionModule)) { return this._SessionModule_36; }
    if ((token === import20.ProtocollRoutingModule)) { return this._ProtocollRoutingModule_37; }
    if ((token === import21.ProtocollModule)) { return this._ProtocollModule_38; }
    if ((token === import22.TextRoutingModule)) { return this._TextRoutingModule_39; }
    if ((token === import23.TextModule)) { return this._TextModule_40; }
    if ((token === import24.AppRoutingModule)) { return this._AppRoutingModule_41; }
    if ((token === import1.AppModule)) { return this._AppModule_42; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_43; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_44; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_45; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_46; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_47; }
    if ((token === import2.Http)) { return this._Http_48; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_49; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_50; }
    if ((token === import0.APP_ID)) { return this._APP_ID_51; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_52; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_53; }
    if ((token === import5.DomSanitizer)) { return this._DomSanitizer_54; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_55; }
    if ((token === import5.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_56; }
    if ((token === import5.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_57; }
    if ((token === import5.EventManager)) { return this._EventManager_58; }
    if ((token === import5.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_59; }
    if ((token === import5.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_60; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_61; }
    if ((token === import5.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_62; }
    if ((token === import0.Testability)) { return this._Testability_63; }
    if ((token === import5.Meta)) { return this._Meta_64; }
    if ((token === import5.Title)) { return this._Title_65; }
    if ((token === import6.ɵi)) { return this._ɵi_66; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_67; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_68; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_69; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_70; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_71; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_72; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_73; }
    if ((token === import25.AlertService)) { return this._AlertService_74; }
    if ((token === import26.OlmService)) { return this._OlmService_75; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_7.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_59 && this._ɵDomSharedStylesHost_59.ngOnDestroy());
    (this.__RouterPreloader_70 && this._RouterPreloader_70.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
