/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/text/text-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './text-create.component.ngfactory';
import * as import4 from './text-edit.component.ngfactory';
import * as import5 from './texts-view.component.ngfactory';
import * as import6 from '../../../../src/app/text/text-create.component';
import * as import7 from '../../../../src/app/services/olm.service';
import * as import8 from '../../../../src/app/text/text-edit.component';
import * as import9 from '../../../../src/app/text/texts-view.component';
class TextRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.TextRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _TextRoutingModule_1:import1.TextRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.TextCreateComponentNgFactory,
      import4.TextEditComponentNgFactory,
      import5.TextsViewComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.TextRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._TextRoutingModule_1 = new import1.TextRoutingModule();
      this._ROUTES_2 = [[
        {
          path: 'text/create/:id',
          component: import6.TextCreateComponent,
          canActivate: [import7.OlmService]
        }
        ,
        {
          path: 'text/edit/:id/:version',
          component: import8.TextEditComponent,
          canActivate: [import7.OlmService]
        }
        ,
        {
          path: 'texts/view',
          component: import9.TextsViewComponent,
          canActivate: [import7.OlmService]
        }

      ]
    ];
    return this._TextRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.TextRoutingModule)) { return this._TextRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TextRoutingModuleNgFactory:import0.NgModuleFactory<import1.TextRoutingModule> = new import0.NgModuleFactory<any>(TextRoutingModuleInjector,import1.TextRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL3RleHQvdGV4dC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC90ZXh0L3RleHQtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
