/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../shared/text-view.component.ngfactory';
import * as import2 from '../../../../src/app/shared/text-view.component';
import * as import3 from '@angular/router';
import * as import4 from '../../../../src/app/services/olm.service';
import * as import5 from './exam-form.component.ngfactory';
import * as import6 from '../../../../src/app/exam/exam-form.component';
import * as import7 from '../../../../src/app/services/alert.service';
import * as import8 from '@angular/common';
import * as import9 from '../../../../src/app/exam/exam-edit.component';
const styles_ExamEditComponent:any[] = ([] as any[]);
export const RenderType_ExamEditComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ExamEditComponent,
  data: {}
}
);
export function View_ExamEditComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{form: 0}),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Prüfungsart bearbeiten'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'text-view',([] as any[]),(null as any),(null as any),(null as any),import1.View_TextViewComponent_0,import1.RenderType_TextViewComponent)),
    import0.ɵdid(57344,(null as any),0,import2.TextViewComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import3.Router
    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'exam-form',([] as any[]),(null as any),(null as any),(null as any),import5.View_ExamFormComponent_0,import5.RenderType_ExamFormComponent)),
      import0.ɵdid(4218880,[[
        1,
        4
      ]
    ],0,import6.ExamFormComponent,[
      import7.AlertService,
      import8.Location
    ]
    ,{
      model: [
        0,
        'model'
      ]
      ,
      parent: [
        1,
        'parent'
      ]
      ,
      submitLabel: [
        2,
        'submitLabel'
      ]

    }
    ,(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import9.ExamEditComponent = v.component;
    ck(v,5,0);
    const currVal_0:any = co.model;
    const currVal_1:any = co;
    const currVal_2:any = co.submitLabel;
    ck(v,8,0,currVal_0,currVal_1,currVal_2);
  },(null as any));
}
function View_ExamEditComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'exam-edit',([] as any[]),(null as any),(null as any),(null as any),View_ExamEditComponent_0,RenderType_ExamEditComponent)),
    import0.ɵdid(57344,(null as any),0,import9.ExamEditComponent,[
      import3.ActivatedRoute,
      import4.OlmService,
      import7.AlertService,
      import3.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ExamEditComponentNgFactory:import0.ComponentFactory<import9.ExamEditComponent> = import0.ɵccf('exam-edit',import9.ExamEditComponent,View_ExamEditComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2V4YW0vZXhhbS1lZGl0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC9leGFtL2V4YW0tZWRpdC5jb21wb25lbnQudHMiLCJuZzovLy9kYXRhL2Vpa2UvZGF0YS9Db2RlL29sbV9jbGllbnQvc3JjL2FwcC9leGFtL2V4YW0tZWRpdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2V4YW0vZXhhbS1lZGl0LmNvbXBvbmVudC50cy5FeGFtRWRpdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5QcsO8ZnVuZ3NhcnQgYmVhcmJlaXRlbjwvaDE+XG5cbjx0ZXh0LXZpZXc+PC90ZXh0LXZpZXc+XG5cbjxleGFtLWZvcm0gW21vZGVsXT1cIm1vZGVsXCIgW3BhcmVudF09XCJ0aGlzXCIgW3N1Ym1pdExhYmVsXT1cInN1Ym1pdExhYmVsXCI+PC9leGFtLWZvcm0+XG4iLCI8ZXhhbS1lZGl0PjwvZXhhbS1lZGl0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO0lBQTJCO0lBRS9CO2dCQUFBOzs7O0lBQUE7S0FBQTtJQUF1QjtJQUV2QjtrQkFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBOzs7SUFBQTtLQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUFtRjs7OztJQUZuRjtJQUVXO0lBQWdCO0lBQWdCO0lBQTNDLFNBQVcsVUFBZ0IsVUFBZ0IsU0FBM0M7Ozs7O0lDSkE7Z0JBQUE7Ozs7O0lBQUE7S0FBQTs7O0lBQUE7OzsifQ==
