/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/exam/exam.module';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '../../../../src/app/shared/shared.module';
import * as import7 from '../../../../src/app/exam/exam-routing.module';
import * as import8 from './exam-create.component.ngfactory';
import * as import9 from './exam-edit.component.ngfactory';
import * as import10 from '../../../../src/app/exam/exam-create.component';
import * as import11 from '../../../../src/app/services/olm.service';
import * as import12 from '../../../../src/app/exam/exam-edit.component';
class ExamModuleInjector extends import0.ɵNgModuleInjector<import1.ExamModule> {
  _RouterModule_0:import2.RouterModule;
  _CommonModule_1:import3.CommonModule;
  _ErrorHandler_2:any;
  _APP_INITIALIZER_3:any[];
  _ApplicationInitStatus_4:import0.ApplicationInitStatus;
  _ɵf_5:import0.ɵf;
  _ApplicationRef_6:any;
  _ApplicationModule_7:import0.ApplicationModule;
  _BrowserModule_8:import4.BrowserModule;
  _ɵba_9:import5.ɵba;
  _FormsModule_10:import5.FormsModule;
  _SharedModule_11:import6.SharedModule;
  _ExamRoutingModule_12:import7.ExamRoutingModule;
  _ExamModule_13:import1.ExamModule;
  __LOCALE_ID_14:any;
  __NgLocalization_15:import3.NgLocaleLocalization;
  __Compiler_16:import0.Compiler;
  __APP_ID_17:any;
  __IterableDiffers_18:any;
  __KeyValueDiffers_19:any;
  __DomSanitizer_20:import4.ɵe;
  __Sanitizer_21:any;
  __HAMMER_GESTURE_CONFIG_22:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import4.EventManager;
  __ɵDomSharedStylesHost_25:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_26:import4.ɵDomRendererFactory2;
  __RendererFactory2_27:any;
  __ɵSharedStylesHost_28:any;
  __Testability_29:import0.Testability;
  __Meta_30:import4.Meta;
  __Title_31:import4.Title;
  __ɵi_32:import5.ɵi;
  _ROUTES_33:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import8.ExamCreateComponentNgFactory,
      import9.ExamEditComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_14():any {
    if ((this.__LOCALE_ID_14 == null)) { (this.__LOCALE_ID_14 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_14;
  }
  get _NgLocalization_15():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_15 == null)) { (this.__NgLocalization_15 = new import3.NgLocaleLocalization(this._LOCALE_ID_14)); }
    return this.__NgLocalization_15;
  }
  get _Compiler_16():import0.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import0.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import0.ɵg()); }
    return this.__APP_ID_17;
  }
  get _IterableDiffers_18():any {
    if ((this.__IterableDiffers_18 == null)) { (this.__IterableDiffers_18 = import0.ɵl()); }
    return this.__IterableDiffers_18;
  }
  get _KeyValueDiffers_19():any {
    if ((this.__KeyValueDiffers_19 == null)) { (this.__KeyValueDiffers_19 = import0.ɵm()); }
    return this.__KeyValueDiffers_19;
  }
  get _DomSanitizer_20():import4.ɵe {
    if ((this.__DomSanitizer_20 == null)) { (this.__DomSanitizer_20 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_20;
  }
  get _Sanitizer_21():any {
    if ((this.__Sanitizer_21 == null)) { (this.__Sanitizer_21 = this._DomSanitizer_20); }
    return this.__Sanitizer_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == null)) { (this.__HAMMER_GESTURE_CONFIG_22 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == null)) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import4.EventManager {
    if ((this.__EventManager_24 == null)) { (this.__EventManager_24 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import0.NgZone))); }
    return this.__EventManager_24;
  }
  get _ɵDomSharedStylesHost_25():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_25 == null)) { (this.__ɵDomSharedStylesHost_25 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_25;
  }
  get _ɵDomRendererFactory2_26():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_26 == null)) { (this.__ɵDomRendererFactory2_26 = new import4.ɵDomRendererFactory2(this._EventManager_24,this._ɵDomSharedStylesHost_25)); }
    return this.__ɵDomRendererFactory2_26;
  }
  get _RendererFactory2_27():any {
    if ((this.__RendererFactory2_27 == null)) { (this.__RendererFactory2_27 = this._ɵDomRendererFactory2_26); }
    return this.__RendererFactory2_27;
  }
  get _ɵSharedStylesHost_28():any {
    if ((this.__ɵSharedStylesHost_28 == null)) { (this.__ɵSharedStylesHost_28 = this._ɵDomSharedStylesHost_25); }
    return this.__ɵSharedStylesHost_28;
  }
  get _Testability_29():import0.Testability {
    if ((this.__Testability_29 == null)) { (this.__Testability_29 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_29;
  }
  get _Meta_30():import4.Meta {
    if ((this.__Meta_30 == null)) { (this.__Meta_30 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_30;
  }
  get _Title_31():import4.Title {
    if ((this.__Title_31 == null)) { (this.__Title_31 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_31;
  }
  get _ɵi_32():import5.ɵi {
    if ((this.__ɵi_32 == null)) { (this.__ɵi_32 = new import5.ɵi()); }
    return this.__ɵi_32;
  }
  createInternal():import1.ExamModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._CommonModule_1 = new import3.CommonModule();
    this._ErrorHandler_2 = import4.ɵa();
    this._APP_INITIALIZER_3 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_4 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_3);
    this._ɵf_5 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_2,this.componentFactoryResolver,this._ApplicationInitStatus_4);
    this._ApplicationRef_6 = this._ɵf_5;
    this._ApplicationModule_7 = new import0.ApplicationModule(this._ApplicationRef_6);
    this._BrowserModule_8 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_9 = new import5.ɵba();
    this._FormsModule_10 = new import5.FormsModule();
    this._SharedModule_11 = new import6.SharedModule();
    this._ExamRoutingModule_12 = new import7.ExamRoutingModule();
    this._ExamModule_13 = new import1.ExamModule();
      this._ROUTES_33 = [[
        {
          path: 'exam/create',
          component: import10.ExamCreateComponent,
          canActivate: [import11.OlmService]
        }
        ,
        {
          path: 'exam/edit/:id/:version',
          component: import12.ExamEditComponent,
          canActivate: [import11.OlmService]
        }

      ]
    ];
    return this._ExamModule_13;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_2; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_3; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_4; }
    if ((token === import0.ɵf)) { return this._ɵf_5; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_6; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_7; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_8; }
    if ((token === import5.ɵba)) { return this._ɵba_9; }
    if ((token === import5.FormsModule)) { return this._FormsModule_10; }
    if ((token === import6.SharedModule)) { return this._SharedModule_11; }
    if ((token === import7.ExamRoutingModule)) { return this._ExamRoutingModule_12; }
    if ((token === import1.ExamModule)) { return this._ExamModule_13; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_14; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_15; }
    if ((token === import0.Compiler)) { return this._Compiler_16; }
    if ((token === import0.APP_ID)) { return this._APP_ID_17; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_18; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_19; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_20; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_21; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import4.EventManager)) { return this._EventManager_24; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_25; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_26; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_27; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_28; }
    if ((token === import0.Testability)) { return this._Testability_29; }
    if ((token === import4.Meta)) { return this._Meta_30; }
    if ((token === import4.Title)) { return this._Title_31; }
    if ((token === import5.ɵi)) { return this._ɵi_32; }
    if ((token === import2.ROUTES)) { return this._ROUTES_33; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_5.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_25 && this._ɵDomSharedStylesHost_25.ngOnDestroy());
  }
}
export const ExamModuleNgFactory:import0.NgModuleFactory<import1.ExamModule> = new import0.NgModuleFactory<any>(ExamModuleInjector,import1.ExamModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2RhdGEvZWlrZS9kYXRhL0NvZGUvb2xtX2NsaWVudC9zcmMvYXBwL2V4YW0vZXhhbS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vZGF0YS9laWtlL2RhdGEvQ29kZS9vbG1fY2xpZW50L3NyYy9hcHAvZXhhbS9leGFtLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
